/**
 * Historical presets generated from Python HISTORICAL_PRESETS
 * Source: src/mahan_vs_attrition/simulation/war_dynamics.py
 *
 * Canonical keys match Python source exactly.
 * Run: PYTHONPATH=src python3 scripts/export_web_presets.py to regenerate.
 */
window.WAR_PRESETS = {
    "gulf_war_1991": {
        "name": "Gulf War 1991",
        "war_type": "limited_war",
        "side_a": "Coalition",
        "side_b": "Iraq",
        "initial_military_a": 95,
        "initial_military_b": 55,
        "initial_economic_a": 95,
        "initial_economic_b": 40,
        "initial_political_will_a": 85,
        "initial_political_will_b": 45,
        "initial_population_support_a": 75,
        "initial_population_support_b": 50,
        "initial_industrial_a": 95,
        "initial_industrial_b": 35,
        "shock_strength": 90,
        "attrition_rate": 30,
        "economic_resilience": 80,
        "political_resilience": 70,
        "shock_strength_a": 95,
        "shock_strength_b": 10,
        "attrition_rate_a": 12,
        "attrition_rate_b": 80,
        "economic_resilience_a": 90,
        "economic_resilience_b": 8,
        "political_resilience_a": 85,
        "political_resilience_b": 5,
        "allow_negotiated_settlement": false,
        "dominance_min_winner_military": 15,
        "dominance_min_gap": 15,
        "historical_classification": "decisive shock",
        "historical_notes": "Coalition air superiority + 100-hour ground campaign. Iraqi military destroyed as fighting force. Clear decisive dynamics."
    },
    "vietnam_war": {
        "name": "Vietnam War",
        "war_type": "limited_war",
        "side_a": "USA/South Vietnam",
        "side_b": "North Vietnam/Viet Cong",
        "initial_military_a": 85,
        "initial_military_b": 50,
        "initial_economic_a": 95,
        "initial_economic_b": 30,
        "initial_political_will_a": 70,
        "initial_political_will_b": 95,
        "initial_population_support_a": 60,
        "initial_population_support_b": 85,
        "initial_industrial_a": 95,
        "initial_industrial_b": 25,
        "shock_strength": 25,
        "attrition_rate": 75,
        "economic_resilience": 70,
        "political_resilience": 40,
        "shock_strength_a": 30,
        "shock_strength_b": 15,
        "attrition_rate_a": 55,
        "attrition_rate_b": 60,
        "economic_resilience_a": 30,
        "economic_resilience_b": 90,
        "political_resilience_a": 45,
        "political_resilience_b": 95,
        "allow_negotiated_settlement": true,
        "earliest_settlement_month": 60,
        "settlement_military_threshold": 20,
        "settlement_exhaustion_threshold": 92,
        "external_support_a": 35,
        "external_support_b": 50,
        "recruitment_capacity_a": 1.3,
        "recruitment_capacity_b": 2.0,
        "historical_classification": "strategic exhaustion",
        "historical_notes": "US military never defeated in field, but political will eroded. North Vietnam sustained losses over 20 years. Terminal event: fall of Saigon. Underlying cause: exhaustion."
    },
    "wwi": {
        "name": "Wwi",
        "war_type": "total_war",
        "side_a": "Allies",
        "side_b": "Central Powers",
        "initial_military_a": 80,
        "initial_military_b": 75,
        "initial_economic_a": 85,
        "initial_economic_b": 70,
        "initial_political_will_a": 80,
        "initial_political_will_b": 75,
        "initial_population_support_a": 75,
        "initial_population_support_b": 70,
        "initial_industrial_a": 85,
        "initial_industrial_b": 75,
        "shock_strength": 40,
        "attrition_rate": 80,
        "economic_resilience": 60,
        "political_resilience": 50,
        "shock_strength_a": 40,
        "shock_strength_b": 35,
        "attrition_rate_a": 75,
        "attrition_rate_b": 95,
        "economic_resilience_a": 65,
        "economic_resilience_b": 28,
        "political_resilience_a": 60,
        "political_resilience_b": 20,
        "allow_negotiated_settlement": true,
        "earliest_settlement_month": 36,
        "settlement_military_threshold": 25,
        "settlement_exhaustion_threshold": 90,
        "historical_classification": "strategic exhaustion",
        "historical_notes": "Western Front = industrial attrition system. Economic blockade degraded German capacity. Final collapse was political and systemic, not battlefield defeat. Hundred Days was operational breakthrough atop exhaustion substrate."
    },
    "franco_prussian": {
        "name": "Franco Prussian",
        "war_type": "limited_war",
        "side_a": "Prussia/Germany",
        "side_b": "France",
        "initial_military_a": 90,
        "initial_military_b": 50,
        "initial_economic_a": 75,
        "initial_economic_b": 80,
        "initial_political_will_a": 90,
        "initial_political_will_b": 40,
        "initial_population_support_a": 85,
        "initial_population_support_b": 35,
        "initial_industrial_a": 80,
        "initial_industrial_b": 75,
        "shock_strength": 90,
        "attrition_rate": 35,
        "economic_resilience": 70,
        "political_resilience": 60,
        "shock_strength_a": 95,
        "shock_strength_b": 15,
        "attrition_rate_a": 18,
        "attrition_rate_b": 90,
        "economic_resilience_a": 80,
        "economic_resilience_b": 10,
        "political_resilience_a": 90,
        "political_resilience_b": 5,
        "allow_negotiated_settlement": false,
        "dominance_min_winner_military": 15,
        "dominance_min_gap": 15,
        "historical_classification": "decisive shock",
        "historical_notes": "Battle of Sedan destroyed French army. But France was already degraded: manpower depletion, economic strain. Shock completed an exhaustion process. Classic iceberg."
    },
    "korean_war": {
        "name": "Korean War",
        "war_type": "coalition",
        "side_a": "UN/South Korea",
        "side_b": "North Korea/China",
        "initial_military_a": 80,
        "initial_military_b": 65,
        "initial_economic_a": 90,
        "initial_economic_b": 40,
        "initial_political_will_a": 70,
        "initial_political_will_b": 85,
        "initial_population_support_a": 65,
        "initial_population_support_b": 80,
        "initial_industrial_a": 90,
        "initial_industrial_b": 35,
        "shock_strength": 50,
        "attrition_rate": 60,
        "economic_resilience": 75,
        "political_resilience": 55,
        "shock_strength_a": 45,
        "shock_strength_b": 50,
        "attrition_rate_a": 70,
        "attrition_rate_b": 65,
        "economic_resilience_a": 60,
        "economic_resilience_b": 70,
        "political_resilience_a": 45,
        "political_resilience_b": 70,
        "allow_negotiated_settlement": true,
        "earliest_settlement_month": 24,
        "settlement_military_threshold": 40,
        "settlement_exhaustion_threshold": 70,
        "external_support_a": 30,
        "external_support_b": 35,
        "recruitment_capacity_a": 1.0,
        "recruitment_capacity_b": 1.3,
        "historical_classification": "mixed / unresolved",
        "historical_notes": "Rapid territorial shifts, Chinese intervention, stalemate. Neither decisive nor purely attritional. Armistice without peace treaty = unresolved."
    },
    "iran_iraq": {
        "name": "Iran Iraq",
        "war_type": "limited_war",
        "side_a": "Iran",
        "side_b": "Iraq",
        "initial_military_a": 60,
        "initial_military_b": 65,
        "initial_economic_a": 50,
        "initial_economic_b": 55,
        "initial_political_will_a": 90,
        "initial_political_will_b": 75,
        "initial_population_support_a": 85,
        "initial_population_support_b": 70,
        "initial_industrial_a": 45,
        "initial_industrial_b": 50,
        "shock_strength": 30,
        "attrition_rate": 85,
        "economic_resilience": 40,
        "political_resilience": 50,
        "shock_strength_a": 25,
        "shock_strength_b": 30,
        "attrition_rate_a": 60,
        "attrition_rate_b": 65,
        "economic_resilience_a": 50,
        "economic_resilience_b": 48,
        "political_resilience_a": 90,
        "political_resilience_b": 70,
        "allow_negotiated_settlement": true,
        "earliest_settlement_month": 72,
        "settlement_military_threshold": 20,
        "settlement_exhaustion_threshold": 92,
        "external_support_a": 35,
        "external_support_b": 40,
        "recruitment_capacity_a": 1.2,
        "recruitment_capacity_b": 1.0,
        "historical_classification": "strategic exhaustion",
        "historical_notes": "Eight years of attritional warfare. Neither side achieved decisive breakthrough. Exhaustion led to ceasefire."
    },
    "wwii": {
        "name": "Wwii",
        "war_type": "total_war",
        "side_a": "Allies",
        "side_b": "Axis",
        "initial_military_a": 85,
        "initial_military_b": 80,
        "initial_economic_a": 95,
        "initial_economic_b": 60,
        "initial_political_will_a": 90,
        "initial_political_will_b": 85,
        "initial_population_support_a": 80,
        "initial_population_support_b": 75,
        "initial_industrial_a": 95,
        "initial_industrial_b": 70,
        "shock_strength": 60,
        "attrition_rate": 80,
        "economic_resilience": 50,
        "political_resilience": 40,
        "shock_strength_a": 55,
        "shock_strength_b": 60,
        "attrition_rate_a": 70,
        "attrition_rate_b": 95,
        "economic_resilience_a": 60,
        "economic_resilience_b": 15,
        "political_resilience_a": 75,
        "political_resilience_b": 18,
        "allow_negotiated_settlement": true,
        "earliest_settlement_month": 48,
        "settlement_military_threshold": 20,
        "settlement_exhaustion_threshold": 92,
        "historical_classification": "strategic exhaustion with decisive accelerators",
        "historical_notes": "Axis defeat driven by industrial mismatch, manpower depletion, fuel collapse, multi-front pressure. Decisive events (Barbarossa failure, Midway, Normandy) accelerated but did not cause defeat. Germany and Japan could not replace losses."
    }
};

window.EXPECTED_HISTORICAL_RESULTS = {
    "gulf_war_1991": {
        "expected_winner_key": "side_a",
        "expected_result": "decisive",
        "historical_duration_months": 7,
        "simulation_target_duration_months": 15,
        "duration_tolerance_months": 10,
        "duration_note": "Simulation month scale includes pre-ground-campaign air and strategic preparation phase.",
        "expected_duration_months": 15
    },
    "vietnam_war": {
        "expected_winner_key": "side_b",
        "expected_result": "exhaustion",
        "historical_duration_months": 108,
        "simulation_target_duration_months": 108,
        "duration_tolerance_months": 30,
        "duration_note": "Vietnam lasted ~20 years. Model targets full duration.",
        "expected_duration_months": 108
    },
    "wwi": {
        "expected_winner_key": "side_a",
        "expected_result": "exhaustion",
        "historical_duration_months": 58,
        "simulation_target_duration_months": 58,
        "duration_tolerance_months": 12,
        "duration_note": "WWI Western Front attrition timeline.",
        "expected_duration_months": 58
    },
    "franco_prussian": {
        "expected_winner_key": "side_a",
        "expected_result": "decisive",
        "historical_duration_months": 9,
        "simulation_target_duration_months": 9,
        "duration_tolerance_months": 3,
        "duration_note": "Franco-Prussian was a short decisive war.",
        "expected_duration_months": 9
    },
    "korean_war": {
        "expected_winner_key": "draw",
        "expected_result": "stalemate",
        "historical_duration_months": 36,
        "simulation_target_duration_months": 36,
        "duration_tolerance_months": 12,
        "duration_note": "Korean War armistice after ~3 years.",
        "expected_duration_months": 36
    },
    "iran_iraq": {
        "expected_winner_key": "draw",
        "expected_result": "exhaustion",
        "historical_duration_months": 96,
        "simulation_target_duration_months": 96,
        "duration_tolerance_months": 12,
        "duration_note": "Eight-year war. Model targets full duration.",
        "expected_duration_months": 96
    },
    "wwii": {
        "expected_winner_key": "side_a",
        "expected_result": "exhaustion",
        "historical_duration_months": 72,
        "simulation_target_duration_months": 72,
        "duration_tolerance_months": 12,
        "duration_note": "WWII in Europe ~6 years. Model targets full duration.",
        "expected_duration_months": 72
    }
};
